version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: afiligen_postgres
    restart: always
    env_file:
      - ./Backend/afiligen-api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - afiligen_network

  afiligen-api:
    build:
      context: ./Backend/afiligen-api
      dockerfile: Dockerfile
    container_name: afiligen_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./Backend/afiligen-api/.env
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/afiligen-api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - afiligen_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres_data:

networks:
  afiligen_network:
    driver: bridge
